const { NxAppWebpackPlugin } = require('@nx/webpack/app-plugin');
const { NxReactWebpackPlugin } = require('@nx/react/webpack-plugin');
const { readFileSync } = require('node:fs');
const { join } = require('node:path');

/**
 * Nx writes one page for the `index` option, so the settings window's page is
 * written here instead. `settings.html` receives only the settings entry's own
 * scripts and styles — never the main window's — so the second window mounts the
 * settings surface alone, and a hashed production build still gets the right
 * filenames.
 */
class SettingsPagePlugin {
  apply(compiler) {
    compiler.hooks.thisCompilation.tap('SettingsPagePlugin', (compilation) => {
      compilation.hooks.processAssets.tap(
        {
          name: 'SettingsPagePlugin',
          stage:
            compiler.webpack.Compilation.PROCESS_ASSETS_STAGE_OPTIMIZE_INLINE,
        },
        () => {
          // This test excludes files generated by HMR (e.g. settings.hot-update.js).
          // Webpack adds one to the updated chunk's own files, so a page that
          // listed it would apply an update no check asked for — which the runtime
          // answers with a TypeError. The index page's plugin states the same rule.
          const hotUpdateAsset = /hot-update\.[cm]?js$/;
          // The runtime and the global stylesheet both belong to every page;
          // the settings entry is this page's own code.
          const files = new Set(
            ['runtime', 'styles', 'settings']
              .flatMap(
                (name) => compilation.entrypoints.get(name)?.getFiles() ?? [],
              )
              .filter((file) => !hotUpdateAsset.test(file)),
          );
          const scripts = [...files].filter((file) => file.endsWith('.js'));
          const styles = [...files].filter((file) => file.endsWith('.css'));
          const html = readFileSync(join(__dirname, 'src', 'settings.html'))
            .toString()
            .replace(
              '</head>',
              `${styles
                .map((file) => `<link rel="stylesheet" href="${file}" />`)
                .join('')}</head>`,
            )
            .replace(
              '</body>',
              `${scripts
                .map((file) => `<script type="module" src="${file}"></script>`)
                .join('')}</body>`,
            );
          compilation.emitAsset(
            'settings.html',
            new compiler.webpack.sources.RawSource(html),
          );
        },
      );
    });
  }
}

module.exports = {
  // rehype-harden publishes a map for src/index.ts without shipping that source.
  ignoreWarnings: [
    {
      module: /node_modules[\\/]rehype-harden[\\/]dist[\\/]index\.js/,
      message: /Failed to parse source map/,
    },
  ],
  output: {
    path: join(__dirname, '../../dist/app/doric-renderer'),
    clean: true,
    // Nx defaults to module scripts while Webpack emits classic worker chunks.
    // Keep their public-path runtime on self.location, not import.meta.url.
    scriptType: 'text/javascript',
  },
  resolve: {
    alias: {
      '@': join(__dirname, 'src'),
    },
  },
  devServer: {
    port: 4200,
    historyApiFallback: {
      index: '/index.html',
      disableDotRule: true,
      htmlAcceptHeaders: ['text/html', 'application/xhtml+xml'],
    },
  },
  plugins: [
    new NxAppWebpackPlugin({
      tsConfig: './tsconfig.app.json',
      compiler: 'babel',
      main: './src/main.tsx',
      additionalEntryPoints: [
        { entryName: 'settings', entryPath: './src/settings.tsx' },
      ],
      index: './src/index.html',
      baseHref: './',
      // Vendored fonts are emitted by css-loader with content hashes; copying
      // them raw as well would ship every font twice. The license still ships.
      assets: [
        './src/favicon.ico',
        {
          input: './src/assets',
          glob: '**/*',
          ignore: ['fonts/*.woff2'],
          output: 'assets',
        },
      ],
      styles: ['./src/styles.css'],
      outputHashing: process.env.NODE_ENV === 'production' ? 'all' : 'none',
      optimization: process.env.NODE_ENV === 'production',
    }),
    new NxReactWebpackPlugin({
      // Uncomment this line if you don't want to use SVGR
      // See: https://react-svgr.com/
      // svgr: false
    }),
    new SettingsPagePlugin(),
  ],
};
